name: Notify Fly.io App of Changes

on:
  push:
    paths:
      - "block_user_agents.conf"
      - "block_ips.conf"

jobs:
  update-flyio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Install Flyctl
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy updates to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_SSH_COMMAND: ${{ secrets.FLY_SSH_COMMAND }}
      - run: |
          $FLY_SSH_COMMAND
