name: Notify Fly.io App of Changes

on:
  push:
    paths:
      - "block_user_agents.conf"
      - "block_ips.conf"

jobs:
  update-flyio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Sử dụng action có sẵn để checkout code từ repository

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master  # Sử dụng action của Fly.io để cài đặt Flyctl

      - name: Deploy updates to Fly.io
        run: |
          # Kết nối vào ứng dụng Fly.io qua SSH và thực hiện script cập nhật
          flyctl ssh console -a $FLY_APP_NAME --command "bash /fly/update_nginx_files.sh"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_SSH_COMMAND: ${{ secrets.FLY_SSH_COMMAND }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
      - run: |
          $FLY_SSH_COMMAND
